pollaplication/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^createpoll/$', views.createPoll, name='createPoll'),
	url(r'^createpoll/newpoll/$', views.newPoll, name='newPoll'),
	url(r'^deletepoll/$', views.deletePoll, name='deletePoll'),
	url(r'^deletepoll/deleted$', views.deleteOnePoll, name='deleteOnePoll'),

]

pollaplication/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^createpoll/$', views.createPoll, name='createPoll'),
	url(r'^createpoll/newpoll/$', views.newPoll, name='newPoll'),
	url(r'^deletepoll/$', views.deletePoll, name='deletePoll'),
	url(r'^deletepoll/deleted$', views.deleteOnePoll, name='deleteOnePoll'),
    url(r'^polls/$', views.polls),

]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.


class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField()

	def __str__(self):              # __unicode__ on Python 2
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now	

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text

pollaplication/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
import datetime
from django.utils import timezone

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def createPoll(request):
	return render(request, 'polls/create_poll.html')	

def newPoll(request):
	if request.method == "POST":
		q = Question(question_text=request.POST['name'], pub_date=timezone.now())
		q.save()

		c = Choice(question = q, choice_text = request.POST['option1'], votes=request.POST['votes1'])
		c.save()

		c = Choice(question = q, choice_text = request.POST['option2'], votes=request.POST['votes2'])
		c.save()

		c = Choice(question = q, choice_text = request.POST['option3'], votes=request.POST['votes3'])
		c.save()

	return HttpResponse("Poll created")

def deletePoll(request):
	poll_list = Question.objects.order_by('-pub_date')
	context = { 'poll_list' : poll_list }
	return render(request, 'polls/delete_poll.html',context)	

def deleteOnePoll(request):

	try:
	    q = Question.objects.get(pk=request.POST['poll'])
	except (KeyError, Question.DoesNotExist):
		return render(request, 'polls/delete_poll.html', {
			'error_message': "Select a poll.",})
	else:
		q.delete()
		return HttpResponse("Poll deleted")

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
import datetime
from django.utils import timezone
from .serializers import QuestionSerializer
from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def createPoll(request):
	return render(request, 'polls/create_poll.html')	

def newPoll(request):
	if request.method == "POST":
		q = Question(question_text=request.POST['name'], pub_date=timezone.now())
		q.save()

		c = Choice(question = q, choice_text = request.POST['option1'], votes=request.POST['votes1'])
		c.save()

		c = Choice(question = q, choice_text = request.POST['option2'], votes=request.POST['votes2'])
		c.save()

		c = Choice(question = q, choice_text = request.POST['option3'], votes=request.POST['votes3'])
		c.save()

	return HttpResponse("Poll created")

def deletePoll(request):
	poll_list = Question.objects.order_by('-pub_date')
	context = { 'poll_list' : poll_list }
	return render(request, 'polls/delete_poll.html',context)	

def deleteOnePoll(request):

	try:
	    q = Question.objects.get(pk=request.POST['poll'])
	except (KeyError, Question.DoesNotExist):
		return render(request, 'polls/delete_poll.html', {
			'error_message': "Select a poll.",})
	else:
		q.delete()
		return HttpResponse("Poll deleted")

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))



class JSONResponse(HttpResponse):
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)


@csrf_exempt
def polls(request):

	if request.method == 'GET':
		encuestas = Question.objects.all()
		serializador = QuestionSerializer(encuestas, many=True)
		return JSONResponse(serializador.data)

	elif request.method == 'POST':
		data = JSONParser().parse(request)
		serializador = QuestionSerializer(data=data)
		if serializador.is_valid():
			serializador.save()
			return JSONResponse(serializador.data, status=201)
	return JSONResponse(serializador.errors, status=400)

polls/templates/polls/create_poll.html
<h1>Create poll</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:newPoll' %}" method="post">
{% csrf_token %}
	<label for="name">Poll name:</label>
    <input type="text" name="name" id="name" />
    <br />
    <label for="option">Option 1:</label>
    <input type="text" name="option1" id="option1" />

    <label for="option">Votes :</label>
    <input type="text" name="votes1" id="votes1" />
    <br />
    <label for="option">Option 2:</label>
    <input type="text" name="option2" id="option2" />

    <label for="option">Votes :</label>
    <input type="text" name="votes2" id="votes2" />
    <br />
    <label for="option">Option 3:</label>
    <input type="text" name="option3" id="option3" />

    <label for="option">Votes :</label>
    <input type="text" name="votes3" id="votes3" />
    <br />
<input type="submit" value="Create" />
</form>

polls/templates/polls/delete_poll.html
<h1>Remove poll</h1>

<h2> Polls availables </h2>

<form action="{% url 'polls:deleteOnePoll' %}" method="post">
{% csrf_token %}
{% for poll in poll_list %}
 	<input type="radio" name="poll" id="poll{{ forloop.counter }}" value="{{ poll.id }}" />
    <label for="poll{{ forloop.counter }}">{{ poll.question_text }}</label><br />
    <br />
{% endfor %}
<input type="submit" value="Delete" />
</form>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
<title> Poll Aplication </title>

<h2> Welcome to poll aplication!!!! </h2>
<p> The list of polls: </p>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>